### ISSUE TITLE
Doesn't always connect

### ISSUE THREAD

**Issue by doowb** [substack/level-party#5]
I have a simple command line script that just opens a connection and gets a value. Every other time I run the script nothing happens and the script ends. There aren't any errors or anything.

If I have another process accessing the database at the same time, the command line script just hangs.

I'm using `level-party` with `levelup-defaults` and `level-sublevel`, so I'm not sure if that combination is causing the problem. My script works fine when I use `level` directly (I just can't access it from multiple processes)

I'm on node v0.12.0.

**Comment by theChumpus** [comment]
I'm also having a similar problem to this!

I have a node function that is calling 'getKeyStream' on the db. When running tests on this function, the first test will run fine (this must get a handle to leveldb directly) but then the subsequent tests will timeout as the key stream does not emit data or end. Running the same tests using 'level' rather than 'level-party' works every time.

I call db.close() on the db after each test but obviously this doesn't close the db like 'level' does, just the connection to it.

Running node v0.10.36 and level-party 1.0.1.

**Comment by mafintosh** [comment]
Could you try this in 2.0.0 and see if this is still an issue?

**Comment by doowb** [comment]
Looks like it's working now, thanks.
